/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clans */
        get: operations["get_clans_api_clans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clan Tree */
        get: operations["get_clan_tree_api_clans__clan_id__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Upload */
        post: operations["post_upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{token}/clan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post New Clan */
        post: operations["post_new_clan_api_uploads__token__clan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{token}/reload/{clan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reload Preview */
        get: operations["get_reload_preview_api_uploads__token__reload__clan_id__get"];
        put?: never;
        /** Post Reload */
        post: operations["post_reload_api_uploads__token__reload__clan_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClanMatch */
        ClanMatch: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persons */
            persons: number;
            /** Matched */
            matched: number;
        };
        /** ClanSummary */
        ClanSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persons */
            persons: number;
            /** Families */
            families: number;
        };
        /** ClanTree */
        ClanTree: {
            clan: components["schemas"]["ClanSummary"];
            /** Persons */
            persons: components["schemas"]["TreePerson"][];
            /** Families */
            families: components["schemas"]["TreeFamily"][];
        };
        /** FieldChange */
        FieldChange: {
            /** Label */
            label: string;
            /** Was */
            was: string;
            /** Now */
            now: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifeDate */
        LifeDate: {
            /** Raw */
            raw: string | null;
            /** Kind */
            kind: string | null;
            /** Year */
            year: number | null;
            /** Month */
            month: number | null;
            /** Day */
            day: number | null;
            /** End Year */
            end_year: number | null;
            /** End Month */
            end_month: number | null;
            /** End Day */
            end_day: number | null;
            /** Phrase */
            phrase: string | null;
        };
        /** MarriageDetails */
        MarriageDetails: {
            /** Family Id */
            family_id: number;
            /** Events */
            events: components["schemas"]["PersonEvent"][];
        };
        /** NewClan */
        NewClan: {
            /** Name */
            name: string;
        };
        /** PersonBrief */
        PersonBrief: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Name */
            name: string;
            /** Years */
            years: string;
            /** Where */
            where: string;
        };
        /** PersonChange */
        PersonChange: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Name */
            name: string;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /** PersonDetails */
        PersonDetails: {
            /** Id */
            id: number;
            /** Clan Id */
            clan_id: number;
            /** Xref */
            xref: string;
            /** Name Raw */
            name_raw: string | null;
            /** Events */
            events: components["schemas"]["PersonEvent"][];
            /** Marriages */
            marriages: components["schemas"]["MarriageDetails"][];
        };
        /** PersonEvent */
        PersonEvent: {
            /** Tag */
            tag: string;
            /** Type */
            type: string | null;
            /** Value */
            value: string | null;
            date: components["schemas"]["LifeDate"] | null;
            /** Place */
            place: string | null;
        };
        /** ReloadPreview */
        ReloadPreview: {
            /** Clan Id */
            clan_id: number;
            /** Clan Name */
            clan_name: string;
            /** Matched */
            matched: number;
            /** Total */
            total: number;
            /** Added */
            added: components["schemas"]["PersonBrief"][];
            /** Changed */
            changed: components["schemas"]["PersonChange"][];
            /** Missing */
            missing: components["schemas"]["PersonBrief"][];
            tree: components["schemas"]["ClanTree"];
        };
        /** ReloadReport */
        ReloadReport: {
            /** Added */
            added: number;
            /** Changed */
            changed: number;
            /** Deleted */
            deleted: number;
            /** Kept */
            kept: number;
        };
        /** ReloadRequest */
        ReloadRequest: {
            /**
             * Delete
             * @default []
             */
            delete: number[];
        };
        /** TreeFamily */
        TreeFamily: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Husband */
            husband: number | null;
            /** Wife */
            wife: number | null;
            /** Children */
            children: number[];
        };
        /** TreePerson */
        TreePerson: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Given */
            given: string | null;
            /** Surname */
            surname: string | null;
            /** Married Surname */
            married_surname: string | null;
            /** Sex */
            sex: ("M" | "F" | "U") | null;
            /** Is Branch Stub */
            is_branch_stub: boolean;
            birth: components["schemas"]["LifeDate"] | null;
            death: components["schemas"]["LifeDate"] | null;
            /** Parent Families */
            parent_families: number[];
            /** Spouse Families */
            spouse_families: number[];
        };
        /** UploadInfo */
        UploadInfo: {
            /** Token */
            token: string;
            /** File Name */
            file_name: string;
            /** Persons */
            persons: number;
            /** Families */
            families: number;
            /** Branch Stubs */
            branch_stubs: number;
            /** Warnings */
            warnings: string[];
            /** Suggested Name */
            suggested_name: string;
            /** Clans */
            clans: components["schemas"]["ClanMatch"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_clans_api_clans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"][];
                };
            };
        };
    };
    get_clan_tree_api_clans__clan_id__tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_upload_api_uploads_post: {
        parameters: {
            query?: {
                file_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_new_clan_api_uploads__token__clan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClan"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reload_preview_api_uploads__token__reload__clan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_reload_api_uploads__token__reload__clan_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
