/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["post_login_api_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Logout */
        post: operations["post_logout_api_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Share Link */
        get: operations["get_share_link_api_clans__clan_id__link_get"];
        put?: never;
        /**
         * Post Share Link
         * @description Выпускает ссылку заново: прежняя перестаёт работать.
         */
        post: operations["post_share_link_api_clans__clan_id__link_post"];
        /**
         * Delete Share Link
         * @description Отзывает ссылку: род закрывается и для тех, кто по ней уже приходил.
         */
        delete: operations["delete_share_link_api_clans__clan_id__link_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clans */
        get: operations["get_clans_api_clans_get"];
        put?: never;
        /**
         * Post Clan
         * @description Новый род с нуля: имя рода и первый человек.
         */
        post: operations["post_clan_api_clans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clan Tree */
        get: operations["get_clan_tree_api_clans__clan_id__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["get_person_api_persons__person_id__get"];
        /** Put Person */
        put: operations["put_person_api_persons__person_id__put"];
        post?: never;
        /** Remove Person */
        delete: operations["remove_person_api_persons__person_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find Persons
         * @description Поиск по всем родам — для ручной связки.
         */
        get: operations["find_persons_api_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clan Links */
        get: operations["get_clan_links_api_clans__clan_id__links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Links */
        get: operations["get_links_api_links_get"];
        put?: never;
        /** Post Link */
        post: operations["post_link_api_links_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidates */
        get: operations["get_candidates_api_links_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{link_id}/see": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Link See
         * @description Уровень связки: скрытую зритель не видит и перейти по ней не может.
         */
        put: operations["put_link_see_api_links__link_id__see_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Link */
        delete: operations["remove_link_api_links__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/links/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Reject */
        post: operations["post_reject_api_links_reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dates/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Parsed Date
         * @description Как поле даты поняло набранное — для подсказки на лету. Непонятное — 400 с причиной.
         */
        get: operations["get_parsed_date_api_dates_parse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person Form */
        get: operations["get_person_form_api_persons__person_id__form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Person */
        post: operations["post_person_api_clans__clan_id__persons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Family Form
         * @description Союз для карточки и формы: венчание, развод, дети по порядку файла.
         */
        get: operations["get_family_form_api_families__family_id__form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/families/{family_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Family */
        put: operations["put_family_api_families__family_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/delete-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Delete Preview */
        get: operations["get_delete_preview_api_persons__person_id__delete_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clan Changes */
        get: operations["get_clan_changes_api_clans__clan_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person Changes */
        get: operations["get_person_changes_api_persons__person_id__changes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Undo */
        post: operations["post_undo_api_clans__clan_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Redo */
        post: operations["post_redo_api_clans__clan_id__redo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{change_id}/undo-to": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Undo To */
        post: operations["post_undo_to_api_changes__change_id__undo_to_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{change_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Revert */
        post: operations["post_revert_api_changes__change_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Clan Status
         * @description Титул рода: пишется в заголовок файла, поэтому переживает выгрузку и перезалив.
         */
        put: operations["put_clan_status_api_clans__clan_id__status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/tags/{name}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tag Usage
         * @description Сколько людей носят метку — чтобы перед удалением сказать, с кого она снимется.
         */
        get: operations["get_tag_usage_api_clans__clan_id__tags__name__usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/tags/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Tag */
        put: operations["put_tag_api_clans__clan_id__tags__name__put"];
        post?: never;
        /** Remove Tag */
        delete: operations["remove_tag_api_clans__clan_id__tags__name__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Photo */
        post: operations["post_photo_api_persons__person_id__photo_post"];
        /** Delete Photo */
        delete: operations["delete_photo_api_persons__person_id__photo_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Export
         * @description Род файлом GEDCOM 5.5.1 — со всеми правками и всем, что пришло из исходного файла.
         */
        get: operations["get_export_api_clans__clan_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Upload */
        post: operations["post_upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{token}/clan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post New Clan */
        post: operations["post_new_clan_api_uploads__token__clan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{token}/reload/{clan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reload Preview */
        get: operations["get_reload_preview_api_uploads__token__reload__clan_id__get"];
        put?: never;
        /** Post Reload */
        post: operations["post_reload_api_uploads__token__reload__clan_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            a: components["schemas"]["Kin"];
            b: components["schemas"]["Kin"];
        };
        /** ChangeInfo */
        ChangeInfo: {
            /** Id */
            id: number;
            /** Summary */
            summary: string;
            /** Author */
            author?: string | null;
            /** Created At */
            created_at: string;
            /** Undone */
            undone: boolean;
            /** Persons */
            persons: number[];
            /** Reverts */
            reverts: number | null;
        };
        /**
         * ClanLink
         * @description Для карты рода: у своего человека есть двойник в другом роду.
         */
        ClanLink: {
            /** Link Id */
            link_id: number;
            /** Person Id */
            person_id: number;
            /**
             * See
             * @default all
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
            /** Created By */
            created_by?: string | null;
            other: components["schemas"]["LinkPerson"];
        };
        /** ClanMatch */
        ClanMatch: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persons */
            persons: number;
            /** Matched */
            matched: number;
        };
        /** ClanStart */
        ClanStart: {
            /** Name */
            name: string;
            /**
             * Status
             * @default plain
             */
            status: string;
            person: components["schemas"]["FirstPerson"];
        };
        /** ClanStatus */
        ClanStatus: {
            /** Status */
            status: string;
        };
        /** ClanSummary */
        ClanSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persons */
            persons: number;
            /** Families */
            families: number;
            /**
             * Status
             * @default plain
             */
            status: string;
        };
        /** ClanTree */
        ClanTree: {
            clan: components["schemas"]["ClanSummary"];
            /** Persons */
            persons: components["schemas"]["TreePerson"][];
            /** Families */
            families: components["schemas"]["TreeFamily"][];
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagDef"][];
        };
        /** Created */
        Created: {
            /** Person Id */
            person_id: number;
            change: components["schemas"]["ChangeInfo"];
        };
        /** DateValue */
        DateValue: {
            /** Gedcom */
            gedcom: string | null;
            /** Ru */
            ru: string;
            /** Input */
            input: string;
        };
        /** DeletePreview */
        DeletePreview: {
            /** Name */
            name: string;
            /** Children */
            children: number;
            /** Descendants */
            descendants: number;
            /** Inlaws */
            inlaws: number;
            /** Stubs */
            stubs: number;
            /** Branch Total */
            branch_total: number;
        };
        /** FamilyChild */
        FamilyChild: {
            /** Id */
            id: number;
            /**
             * Pedigree
             * @enum {string}
             */
            pedigree: "birth" | "adopted" | "foster";
        };
        /** FamilyFields */
        FamilyFields: {
            /** Marriage */
            marriage?: string | null;
            /** Place */
            place?: string | null;
            /**
             * Divorced
             * @default false
             */
            divorced: boolean;
            /** Divorce */
            divorce?: string | null;
            /** Children */
            children?: number[] | null;
            /**
             * Unlink
             * @default []
             */
            unlink: number[];
        };
        /** FamilyForm */
        FamilyForm: {
            /** Id */
            id: number;
            /** Clan Id */
            clan_id: number;
            /** Xref */
            xref: string;
            /** Husband */
            husband: number | null;
            /** Wife */
            wife: number | null;
            marriage: components["schemas"]["DateValue"];
            /** Place */
            place: string | null;
            /** Divorced */
            divorced: boolean;
            divorce: components["schemas"]["DateValue"];
            /** Children */
            children: components["schemas"]["FamilyChild"][];
        };
        /** FieldChange */
        FieldChange: {
            /** Label */
            label: string;
            /** Was */
            was: string;
            /** Now */
            now: string;
        };
        /** FirstPerson */
        FirstPerson: {
            /**
             * Given
             * @default
             */
            given: string;
            /**
             * Surname
             * @default
             */
            surname: string;
            /**
             * Sex
             * @default U
             * @enum {string}
             */
            sex: "M" | "F" | "U";
            /**
             * Birth
             * @default
             */
            birth: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Kin
         * @description Окружение кандидата: по нему тёзки из разных семей расходятся сразу.
         *     Родственник, который сам ждёт проверки, узнаётся по id в очереди; связанный — по полю linked.
         */
        Kin: {
            person: components["schemas"]["LinkPerson"];
            /** Parents */
            parents: components["schemas"]["KinPerson"][];
            /** Spouses */
            spouses: components["schemas"]["KinPerson"][];
            /** Children */
            children: components["schemas"]["KinPerson"][];
        };
        /** KinChanges */
        KinChanges: {
            /**
             * Parents
             * @default []
             */
            parents: components["schemas"]["ParentChange"][];
            /**
             * Spouses
             * @default []
             */
            spouses: components["schemas"]["SpouseChange"][];
            /** Marriage Order */
            marriage_order?: number[] | null;
            /**
             * Marriage Order Auto
             * @default false
             */
            marriage_order_auto: boolean;
        };
        /**
         * KinPerson
         * @description Родственник кандидата: имя, а если он сам связан с другим родом — с кем.
         */
        KinPerson: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            linked?: components["schemas"]["LinkPerson"] | null;
        };
        /** LifeDate */
        LifeDate: {
            /** Raw */
            raw: string | null;
            /** Kind */
            kind: string | null;
            /** Year */
            year: number | null;
            /** Month */
            month: number | null;
            /** Day */
            day: number | null;
            /** End Year */
            end_year: number | null;
            /** End Month */
            end_month: number | null;
            /** End Day */
            end_day: number | null;
            /** Phrase */
            phrase: string | null;
        };
        /** Link */
        Link: {
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /**
             * See
             * @default all
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
            /** Created By */
            created_by?: string | null;
            /** Created At */
            created_at: string;
            a: components["schemas"]["LinkPerson"];
            b: components["schemas"]["LinkPerson"];
        };
        /** LinkPerson */
        LinkPerson: {
            /** Id */
            id: number;
            /** Clan Id */
            clan_id: number;
            /** Clan Name */
            clan_name: string;
            /** Name */
            name: string;
            /** Born */
            born: number | null;
            /** Died */
            died: number | null;
        };
        /** LinkSee */
        LinkSee: {
            /**
             * See
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
        };
        /** LoginForm */
        LoginForm: {
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** MarriageDetails */
        MarriageDetails: {
            /** Family Id */
            family_id: number;
            /** Events */
            events: components["schemas"]["PersonEvent"][];
        };
        /** Me */
        Me: {
            /** Name */
            name?: string | null;
            /** Guarded */
            guarded: boolean;
            /**
             * Clans
             * @default []
             */
            clans: number[];
        };
        /** NewClan */
        NewClan: {
            /** Name */
            name: string;
        };
        /** NewLink */
        NewLink: {
            /** A */
            a: number;
            /** B */
            b: number;
            /** Note */
            note?: string | null;
            /**
             * Replace
             * @default false
             */
            replace: boolean;
            /**
             * See
             * @default all
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
        };
        /** NewPerson */
        NewPerson: {
            /**
             * @default {
             *       "notes": [],
             *       "new_tags": {}
             *     }
             */
            fields: components["schemas"]["PersonFields"];
            relation: components["schemas"]["Relation"];
            /** Existing Id */
            existing_id?: number | null;
        };
        /**
         * NoteForm
         * @description Заметка человека со своим уровнем видимости.
         */
        NoteForm: {
            /** Text */
            text: string;
            /**
             * See
             * @default clan
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
        };
        /** PairDecision */
        PairDecision: {
            /** A */
            a: number;
            /** B */
            b: number;
        };
        /**
         * ParentChange
         * @description Семья, где человек записан ребёнком: оставить, отвязать или перенести в другую; тип родства.
         */
        ParentChange: {
            /** Family Id */
            family_id: number;
            /**
             * Action
             * @default keep
             * @enum {string}
             */
            action: "keep" | "drop" | "move";
            /** To Family Id */
            to_family_id?: number | null;
            /** Pedigree */
            pedigree?: ("birth" | "adopted" | "foster") | null;
        };
        /** ParsedDate */
        ParsedDate: {
            /** Gedcom */
            gedcom: string | null;
            /** Ru */
            ru: string;
            /** Kind */
            kind: string;
        };
        /** PersonBrief */
        PersonBrief: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Name */
            name: string;
            /** Years */
            years: string;
            /** Where */
            where: string;
        };
        /** PersonChange */
        PersonChange: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Name */
            name: string;
            /** Changes */
            changes: components["schemas"]["FieldChange"][];
        };
        /** PersonDetails */
        PersonDetails: {
            /** Id */
            id: number;
            /** Clan Id */
            clan_id: number;
            /** Xref */
            xref: string;
            /** Name Raw */
            name_raw: string | null;
            /** Events */
            events: components["schemas"]["PersonEvent"][];
            /** Marriages */
            marriages: components["schemas"]["MarriageDetails"][];
        };
        /** PersonEvent */
        PersonEvent: {
            /** Tag */
            tag: string;
            /** Type */
            type: string | null;
            /** Value */
            value: string | null;
            date: components["schemas"]["LifeDate"] | null;
            /** Place */
            place: string | null;
            /**
             * See
             * @default all
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
        };
        /**
         * PersonFields
         * @description Что форма присылает. Даты — как набраны, по-русски или строкой GEDCOM.
         */
        PersonFields: {
            /** Given */
            given?: string | null;
            /** Surname */
            surname?: string | null;
            /** Married Surname */
            married_surname?: string | null;
            /** Sex */
            sex?: ("M" | "F" | "U") | null;
            /** Birth */
            birth?: string | null;
            /** Death */
            death?: string | null;
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["NoteForm"][];
            /** Tags */
            tags?: string[] | null;
            /**
             * New Tags
             * @default {}
             */
            new_tags: {
                [key: string]: string;
            };
            /** Burnt */
            burnt?: boolean | null;
            /** See */
            see?: ("all" | "clan" | "hidden") | null;
            /** See Dates */
            see_dates?: ("all" | "clan" | "hidden") | null;
            /** See Portrait */
            see_portrait?: ("all" | "clan" | "hidden") | null;
            /** Heir */
            heir?: boolean | null;
            /** Portrait */
            portrait?: ("auto" | "silhouette" | "none") | null;
            kin?: components["schemas"]["KinChanges"] | null;
        };
        /**
         * PersonForm
         * @description Что показывает форма правки.
         */
        PersonForm: {
            /** Id */
            id: number;
            /** Clan Id */
            clan_id: number;
            /** Given */
            given: string | null;
            /** Surname */
            surname: string | null;
            /** Married Surname */
            married_surname: string | null;
            /** Sex */
            sex: ("M" | "F" | "U") | null;
            birth: components["schemas"]["DateValue"];
            death: components["schemas"]["DateValue"];
            /** Notes */
            notes: components["schemas"]["NoteForm"][];
            /** Tags */
            tags: string[];
            /** Burnt */
            burnt: boolean;
            /**
             * See
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
            /**
             * See Dates
             * @enum {string}
             */
            see_dates: "all" | "clan" | "hidden";
            /**
             * See Portrait
             * @enum {string}
             */
            see_portrait: "all" | "clan" | "hidden";
            /** Heir */
            heir: boolean;
            /**
             * Portrait
             * @enum {string}
             */
            portrait: "auto" | "silhouette" | "none";
            /** Photo */
            photo: string | null;
            /**
             * Marriage Order Manual
             * @default false
             */
            marriage_order_manual: boolean;
        };
        /**
         * Relation
         * @description Куда встаёт человек. kind: child, parent, spouse, sibling.
         *
         *     child — к person_id; other_id — второй родитель (None — неизвестен), new_union — отдельный союз.
         *     parent — к person_id, роль по полу нового человека; separate — отдельной семьёй (родные при приёмных).
         *     spouse — новый союз с person_id.
         *     sibling — к person_id; parents: both, father, mother.
         */
        Relation: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "child" | "parent" | "spouse" | "sibling";
            /** Person Id */
            person_id: number;
            /** Other Id */
            other_id?: number | null;
            /**
             * Parents
             * @default both
             * @enum {string}
             */
            parents: "both" | "father" | "mother";
            /**
             * Pedigree
             * @default birth
             * @enum {string}
             */
            pedigree: "birth" | "adopted" | "foster";
            /**
             * Separate
             * @default false
             */
            separate: boolean;
        };
        /** ReloadPreview */
        ReloadPreview: {
            /** Clan Id */
            clan_id: number;
            /** Clan Name */
            clan_name: string;
            /** Matched */
            matched: number;
            /** Total */
            total: number;
            /** Added */
            added: components["schemas"]["PersonBrief"][];
            /** Changed */
            changed: components["schemas"]["PersonChange"][];
            /** Missing */
            missing: components["schemas"]["PersonBrief"][];
            tree: components["schemas"]["ClanTree"];
        };
        /** ReloadReport */
        ReloadReport: {
            /** Added */
            added: number;
            /** Changed */
            changed: number;
            /** Deleted */
            deleted: number;
            /** Kept */
            kept: number;
        };
        /** ReloadRequest */
        ReloadRequest: {
            /**
             * Delete
             * @default []
             */
            delete: number[];
        };
        /**
         * ShareInfo
         * @description Ссылка зрителям на род: адрес показывается редактору целиком, чтобы его можно было отдать.
         */
        ShareInfo: {
            /** Url */
            url: string;
            /** Created At */
            created_at: string;
            /** Opened */
            opened: number;
            /** Opened At */
            opened_at?: string | null;
        };
        /**
         * SpouseChange
         * @description Союз человека: оставить, выйти из него или поставить на своё место другого.
         */
        SpouseChange: {
            /** Family Id */
            family_id: number;
            /**
             * Action
             * @default keep
             * @enum {string}
             */
            action: "keep" | "drop" | "replace";
            /** To Person Id */
            to_person_id?: number | null;
        };
        /** TagChange */
        TagChange: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** TagDef */
        TagDef: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** TreeFamily */
        TreeFamily: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Husband */
            husband: number | null;
            /** Wife */
            wife: number | null;
            /** Children */
            children: number[];
            /**
             * Child Pedigree
             * @default []
             */
            child_pedigree: string[];
            /**
             * Divorced
             * @default false
             */
            divorced: boolean;
        };
        /** TreePerson */
        TreePerson: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Given */
            given: string | null;
            /** Surname */
            surname: string | null;
            /** Married Surname */
            married_surname: string | null;
            /** Sex */
            sex: ("M" | "F" | "U") | null;
            /** Is Branch Stub */
            is_branch_stub: boolean;
            birth: components["schemas"]["LifeDate"] | null;
            death: components["schemas"]["LifeDate"] | null;
            /** Parent Families */
            parent_families: number[];
            /** Spouse Families */
            spouse_families: number[];
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /**
             * Burnt
             * @default false
             */
            burnt: boolean;
            /**
             * See
             * @default all
             * @enum {string}
             */
            see: "all" | "clan" | "hidden";
            /**
             * See Dates
             * @default clan
             * @enum {string}
             */
            see_dates: "all" | "clan" | "hidden";
            /**
             * See Portrait
             * @default all
             * @enum {string}
             */
            see_portrait: "all" | "clan" | "hidden";
            /**
             * Heir
             * @default false
             */
            heir: boolean;
            /**
             * Portrait
             * @default auto
             * @enum {string}
             */
            portrait: "auto" | "silhouette" | "none";
            /** Photo */
            photo?: string | null;
        };
        /** UploadInfo */
        UploadInfo: {
            /** Token */
            token: string;
            /** File Name */
            file_name: string;
            /** Persons */
            persons: number;
            /** Families */
            families: number;
            /** Branch Stubs */
            branch_stubs: number;
            /** Warnings */
            warnings: string[];
            /** Suggested Name */
            suggested_name: string;
            /** Clans */
            clans: components["schemas"]["ClanMatch"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    post_login_api_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginForm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_logout_api_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    get_share_link_api_clans__clan_id__link_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_share_link_api_clans__clan_id__link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_share_link_api_clans__clan_id__link_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_clans_api_clans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"][];
                };
            };
        };
    };
    post_clan_api_clans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClanStart"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clan_tree_api_clans__clan_id__tree_get: {
        parameters: {
            query?: {
                as_viewer?: number | null;
            };
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_api_persons__person_id__get: {
        parameters: {
            query?: {
                as_viewer?: number | null;
            };
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetails"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_person_api_persons__person_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonFields"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_person_api_persons__person_id__delete: {
        parameters: {
            query?: {
                branch?: boolean;
            };
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    find_persons_api_persons_get: {
        parameters: {
            query: {
                q: string;
                exclude_clan?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinkPerson"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clan_links_api_clans__clan_id__links_get: {
        parameters: {
            query?: {
                as_viewer?: number | null;
            };
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanLink"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_links_api_links_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"][];
                };
            };
        };
    };
    post_link_api_links_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewLink"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidates_api_links_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"][];
                };
            };
        };
    };
    put_link_see_api_links__link_id__see_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LinkSee"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Link"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_link_api_links__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_reject_api_links_reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_parsed_date_api_dates_parse_get: {
        parameters: {
            query?: {
                text?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParsedDate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_form_api_persons__person_id__form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_person_api_clans__clan_id__persons_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPerson"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Created"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_family_form_api_families__family_id__form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyForm"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_family_api_families__family_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                family_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FamilyFields"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_delete_preview_api_persons__person_id__delete_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeletePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_clan_changes_api_clans__clan_id__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_person_changes_api_persons__person_id__changes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_undo_api_clans__clan_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_redo_api_clans__clan_id__redo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_undo_to_api_changes__change_id__undo_to_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_revert_api_changes__change_id__revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                change_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_clan_status_api_clans__clan_id__status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClanStatus"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tag_usage_api_clans__clan_id__tags__name__usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_tag_api_clans__clan_id__tags__name__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_tag_api_clans__clan_id__tags__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_photo_api_persons__person_id__photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_photo_api_persons__person_id__photo_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangeInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_export_api_clans__clan_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_upload_api_uploads_post: {
        parameters: {
            query?: {
                file_name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_new_clan_api_uploads__token__clan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewClan"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reload_preview_api_uploads__token__reload__clan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_reload_api_uploads__token__reload__clan_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReloadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReloadReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
