/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clans */
        get: operations["get_clans_api_clans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clans/{clan_id}/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clan Tree */
        get: operations["get_clan_tree_api_clans__clan_id__tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClanSummary */
        ClanSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Persons */
            persons: number;
            /** Families */
            families: number;
        };
        /** ClanTree */
        ClanTree: {
            clan: components["schemas"]["ClanSummary"];
            /** Persons */
            persons: components["schemas"]["TreePerson"][];
            /** Families */
            families: components["schemas"]["TreeFamily"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LifeDate */
        LifeDate: {
            /** Raw */
            raw: string | null;
            /** Kind */
            kind: string | null;
            /** Year */
            year: number | null;
            /** Month */
            month: number | null;
            /** Day */
            day: number | null;
            /** End Year */
            end_year: number | null;
            /** End Month */
            end_month: number | null;
            /** End Day */
            end_day: number | null;
            /** Phrase */
            phrase: string | null;
        };
        /** TreeFamily */
        TreeFamily: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Husband */
            husband: number | null;
            /** Wife */
            wife: number | null;
            /** Children */
            children: number[];
        };
        /** TreePerson */
        TreePerson: {
            /** Id */
            id: number;
            /** Xref */
            xref: string;
            /** Given */
            given: string | null;
            /** Surname */
            surname: string | null;
            /** Married Surname */
            married_surname: string | null;
            /** Sex */
            sex: ("M" | "F" | "U") | null;
            /** Is Branch Stub */
            is_branch_stub: boolean;
            birth: components["schemas"]["LifeDate"] | null;
            death: components["schemas"]["LifeDate"] | null;
            /** Parent Families */
            parent_families: number[];
            /** Spouse Families */
            spouse_families: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_clans_api_clans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanSummary"][];
                };
            };
        };
    };
    get_clan_tree_api_clans__clan_id__tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClanTree"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
